#!/usr/bin/perl

#use strict;

my $parse = 0;
my $obj, my $port;

while ($_ = <STDIN>) {

    # wait until servojb defs
    # 
    if (/:servobj \(servobj/) { $parse = 1; }
    
    # stop before timeobj defs
    # 
    if (/:timeobj \(timeobj/) { $parse = 0; }
    
    if ($parse) {
        
        if (/: \(([\w|\d|\-]+)/) {
            $obj = $1;
        }
        
        if ($obj and /:port \((\d+)\)/) {
            $port = $1;
            print "$obj\n$port\n";

            my @fw1_objects = ($obj, $port);
            my $repeated = 0;

            $obj = $port = "";
        }
    }
}

