#!/usr/bin/perl

use strict;

while( my $filename = <STDIN> )  {

    open (FILE, $filename) or die "Unable to open file $filename";

    my $sig_name;
    if ($filename =~ /([\w\d-_]+)\.rules/) { $sig_name = $1; }
    
    while ($_ = <FILE>) {
        if (/sid:([^;]+)/) {
            my $sid = $1;
            print ("$sid\n$sig_name\n");
        }
    }
    close($filename);
}

