---
# Database Backups.
# Input params:
# username: useranme to run the playbook
# database_name: The database hostname
# database_host: database host
# database_password: user password
# dbuser: database username 
# dst_folder: destination folder
# ansible-playbook -v --extra-vars="filename=configuration_ddbb_backup.1376393875.tar.gz backup_type=configuration database=alienvault ddbb_host=192.168.230.5 ddbb_user=root ddbb_password=GqgDLUTN46 dst_folder=/tmp/" ddbb_backup.yml
- hosts: ossims
  user: root
  vars_files:
    - /etc/ossim/ansible/playbooks/backups/{{ backup_type }}/backup_vars.yml
  tasks:
    - name: Get the current date.
      action: shell date '+%s'
      register: CURRENT_DATE
    - name: Create backup folder
      action: shell  mkdir -p /tmp/{{backup_type}}_ddbb_backup_{{ CURRENT_DATE.stdout }}
    - name: Copy Alienvault files to backup folder
      action: shell mysqldump alienvault {{ item }} -h {{ ddbb_host }} -u {{ ddbb_user }} -p{{ ddbb_password }} -c -n -t -f --no-autocommit --skip-triggers --single-transaction --quick --hex-blob --insert-ignore > /tmp/{{backup_type}}_ddbb_backup_{{ CURRENT_DATE.stdout }}/{{item}}_backup.sql
      with_items:  alienvault.tables 
    - name: Copy files AVCenter to backup folder
      action: shell mysqldump avcenter {{ item }} -h {{ ddbb_host }} -u {{ ddbb_user }} -p{{ ddbb_password }} -c -n -t -f --no-autocommit --skip-triggers --single-transaction --quick --hex-blob --insert-ignore > /tmp/{{backup_type}}_ddbb_backup_{{ CURRENT_DATE.stdout }}/{{item}}_backup.sql
      with_items:  avcenter.tables  
    - name: Copy files Alienvault SIEM to backup folder
      action: shell mysqldump alienvault_siem {{ item }} -h {{ ddbb_host }} -u {{ ddbb_user }} -p{{ ddbb_password }} -c -n -t -f --no-autocommit --skip-triggers --single-transaction --quick --hex-blob --insert-ignore > /tmp/{{backup_type}}_ddbb_backup_{{ CURRENT_DATE.stdout }}/{{item}}_backup.sql
      with_items:  alienvault_siem.tables
    - name: Copy files Alienvault ASEC to backup folder
      action: shell mysqldump alienvault_asec {{ item }} -h {{ ddbb_host }} -u {{ ddbb_user }} -p{{ ddbb_password }} -c -n -t -f --no-autocommit --skip-triggers --single-transaction --quick --hex-blob --insert-ignore > /tmp/{{backup_type}}_ddbb_backup_{{ CURRENT_DATE.stdout }}/{{item}}_backup.sql
      with_items:  alienvault_asec.tables      
    - name: Full Databases backups
      action: shell mysqldump {{ item }} -h {{ ddbb_host }} -u {{ ddbb_user }} -p{{ ddbb_password }} -c -n -t -f --no-autocommit --skip-triggers --single-transaction --quick --hex-blob --insert-ignore > /tmp/{{backup_type}}_ddbb_backup_{{ CURRENT_DATE.stdout }}/{{item}}_backup.sql
      with_items: fulldatabases
    - debug: msg="currentdate -> {{CURRENT_DATE}}"
    - debug: msg="bktype -> {{backup_type}}"       
    - name: Compress the backup folder      
      action: shell tar -zcvf {{dst_folder}}/{{backup_type}}_ddbb_backup.{{ CURRENT_DATE.stdout }}.tar.gz --directory /tmp/{{backup_type}}_ddbb_backup_{{ CURRENT_DATE.stdout }}/ .
    - name: Remove the temporal folder
      action: shell rm -rf /tmp/{{backup_type}}_ddbb_backup_{{ CURRENT_DATE.stdout }}