-- cisco-ids
-- plugin_id: 1515
--
-- $Id: cisco-ids.sql,v 1.2 2007/03/26 18:36:15 juanmals Exp $
--
DELETE FROM plugin WHERE id = "1515";
DELETE FROM plugin_sid where plugin_id = "1515";


INSERT INTO plugin (id, type, name, description) VALUES (1515, 1, 'cisco-ids', 'Cisco Secure IDS');

INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1000, NULL, NULL, 'IP options-Bad Option List');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 10000, NULL, NULL, 'IP-Spoof Interface 1');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1001, NULL, NULL, 'IP options-Record Packet Route');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1002, NULL, NULL, 'IP options-Timestamp');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1003, NULL, NULL, 'IP options-Provide s,c,h,tcc');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1004, NULL, NULL, 'IP options-Loose Source Route');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1005, NULL, NULL, 'IP options-SATNET ID');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1006, NULL, NULL, 'IP options-Strict Source Route');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1100, NULL, NULL, 'IP Fragment Attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 11000, NULL, NULL, 'KaZaA v2 UDP Client Probe');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 11001, NULL, NULL, 'Gnutella Client Request');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 11002, NULL, NULL, 'Gnutella Server Reply');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 11003, NULL, NULL, 'Qtella File Request');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 11004, NULL, NULL, 'Bearshare file request ');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 11005, NULL, NULL, 'KaZaA GET Request');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 11006, NULL, NULL, 'Gnucleus file request');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 11007, NULL, NULL, 'Limewire File Request');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 11008, NULL, NULL, 'Morpheus File Request');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 11009, NULL, NULL, 'Phex File Request');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1101, NULL, NULL, 'Unknown IP Protocol');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 11010, NULL, NULL, 'Swapper File Request');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 11011, NULL, NULL, 'XoloX File Request');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 11012, NULL, NULL, 'GTK-Gnutella File Request');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 11013, NULL, NULL, 'Mutella File Request ');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 11014, NULL, NULL, 'Hotline Client Login');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 11015, NULL, NULL, 'Hotline File Transfer');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 11016, NULL, NULL, 'Hotline Tracker Login');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1102, NULL, NULL, 'Impossible IP Packet');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1103, NULL, NULL, 'IP Fragments Overlap');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1104, NULL, NULL, 'IP Localhost Source Spoof');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1107, NULL, NULL, 'RFC 1918 Addresses Seen');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1108, NULL, NULL, 'IP Packet with Proto 11');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 11200, NULL, NULL, 'Yahoo Messenger Activity');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 11201, NULL, NULL, 'MSN Messenger Activity');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 11202, NULL, NULL, 'AOL / ICQ Activity');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 11203, NULL, NULL, 'IRC Channel Join');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 11204, NULL, NULL, 'Jabber Activity [new.gif]');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1200, NULL, NULL, 'IP Fragmentation Buffer Full');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1201, NULL, NULL, 'IP Fragment Overlap');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1202, NULL, NULL, 'IP Fragment Overrun - Datagram Too Long');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1203, NULL, NULL, 'IP Fragment Overwrite - Data is Overwritten');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1204, NULL, NULL, 'IP Fragment Missing Initial Fragment ');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1205, NULL, NULL, 'IP Fragment Too Many Datagrams');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1206, NULL, NULL, 'IP Fragment Too Small');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1207, NULL, NULL, 'IP Fragment Too Many Frags');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1208, NULL, NULL, 'IP Fragment Incomplete Datagram');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1220, NULL, NULL, 'Jolt2 Fragment Reassembly DoS attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1300, NULL, NULL, 'TCP Segment Overwrite');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 2000, NULL, NULL, 'ICMP Echo Reply');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 2001, NULL, NULL, 'ICMP Host Unreachable');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 2002, NULL, NULL, 'ICMP Source Quench');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 2003, NULL, NULL, 'ICMP Redirect');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 2004, NULL, NULL, 'ICMP Echo Request');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 2005, NULL, NULL, 'ICMP Time Exceeded for a Datagram');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 2006, NULL, NULL, 'ICMP Parameter Problem on Datagram');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 2007, NULL, NULL, 'ICMP Timestamp Request');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 2008, NULL, NULL, 'ICMP Timestamp Reply');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 2009, NULL, NULL, 'ICMP Information Request');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 2010, NULL, NULL, 'ICMP Information Reply');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 2011, NULL, NULL, 'ICMP Address Mask Request');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 2012, NULL, NULL, 'ICMP Address Mask Reply');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 2100, NULL, NULL, 'ICMP Network Sweep w/Echo');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 2101, NULL, NULL, 'ICMP Network Sweep w/Timestamp');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 2102, NULL, NULL, 'ICMP Network Sweep w/Address Mask');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 2150, NULL, NULL, 'Fragmented ICMP Traffic');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 2151, NULL, NULL, 'Large ICMP Traffic');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 2152, NULL, NULL, 'ICMP Flood');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 2153, NULL, NULL, 'Smurf');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 2154, NULL, NULL, 'Ping of Death Attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 2155, NULL, NULL, 'Modem DoS');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3000, NULL, NULL, 'TCP Ports');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3001, NULL, NULL, 'TCP Port Sweep');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3002, NULL, NULL, 'TCP SYN Port Sweep');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3003, NULL, NULL, 'TCP Frag SYN Port Sweep');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3005, NULL, NULL, 'TCP FIN Port Sweep');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3006, NULL, NULL, 'TCP Frag FIN Port Sweep');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3010, NULL, NULL, 'TCP High Port Sweep');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3011, NULL, NULL, 'TCP FIN High Port Sweep');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3012, NULL, NULL, 'TCP Frag FIN High Port Sweep');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3015, NULL, NULL, 'TCP Null Port Sweep');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3016, NULL, NULL, 'TCP Frag Null Port Sweep');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3020, NULL, NULL, 'TCP SYN FIN Port Sweep');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3021, NULL, NULL, 'TCP Frag SYN FIN Port Sweep');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3030, NULL, NULL, 'TCP SYN Host Sweep');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3031, NULL, NULL, 'TCP FRAG SYN Host Sweep');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3032, NULL, NULL, 'TCP FIN Host Sweep');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3033, NULL, NULL, 'TCP FRAG FIN Host Sweep');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3034, NULL, NULL, 'TCP NULL Host Sweep');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3035, NULL, NULL, 'TCP FRAG NULL Host Sweep');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3036, NULL, NULL, 'TCP SYN FIN Host Sweep');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3037, NULL, NULL, 'TCP FRAG SYN FIN Host Sweep');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3038, NULL, NULL, 'Fragmented NULL TCP Packet');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3039, NULL, NULL, 'Fragmented Orphaned FIN packet');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3040, NULL, NULL, 'NULL TCP Packet');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3041, NULL, NULL, 'SYN/FIN Packet');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3042, NULL, NULL, 'Orphaned Fin Packet');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3043, NULL, NULL, 'Fragmented SYN/FIN Packet');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3045, NULL, NULL, 'Queso Sweep');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3046, NULL, NULL, 'NMAP OS Fingerprint');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3050, NULL, NULL, 'Half-open SYN Attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3100, NULL, NULL, 'Smail Attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3101, NULL, NULL, 'Sendmail Invalid Recipient');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3102, NULL, NULL, 'Sendmail Invalid Sender');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3103, NULL, NULL, 'Sendmail Reconnaissance');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3104, NULL, NULL, 'Archaic Sendmail Attacks');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3105, NULL, NULL, 'Sendmail Decode Alias');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3106, NULL, NULL, 'Mail Spam');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3107, NULL, NULL, 'Majordomo Execute Attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3108, NULL, NULL, 'MIME Overflow Bug');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3109, NULL, NULL, 'Long SMTP Command');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3110, NULL, NULL, 'Suspicious Mail Attachment');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3111, NULL, NULL, 'W32 Sircam Malicious Code');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3112, NULL, NULL, 'Lotus Domino Mail Loop DoS');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3114, NULL, NULL, 'FetchMail Arbitrary Code Execution');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3115, NULL, NULL, 'Sendmail Data Header Overflow');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3116, NULL, NULL, 'Netbus');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3117, NULL, NULL, 'KLEZ worm ');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3118, NULL, NULL, 'rwhoisd format string');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3119, NULL, NULL, 'WS_FTP STAT overflow ');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3120, NULL, NULL, 'ANTS virus');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3121, NULL, NULL, 'Vintra MailServer EXPN DoS');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3122, NULL, NULL, 'SMTP EXPN root Recon');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3123, NULL, NULL, 'NetBus Pro Traffic');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3124, NULL, NULL, 'Sendmail prescan Memory Corruption');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3150, NULL, NULL, 'FTP Remote Command Execution');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3151, NULL, NULL, 'FTP SYST Command Attempt');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3152, NULL, NULL, 'FTP CWD ~root');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3153, NULL, NULL, 'FTP Improper Address Specified');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3154, NULL, NULL, 'FTP Improper Port Specified');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3155, NULL, NULL, 'FTP RETR Pipe Filename Command Execution');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3156, NULL, NULL, 'FTP STOR Pipe Filename Command Execution');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3157, NULL, NULL, 'FTP PASV Port Spoof');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3158, NULL, NULL, 'FTP SITE EXEC Format String');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3159, NULL, NULL, 'FTP PASS Suspicious Length');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3160, NULL, NULL, 'Cesar FTP Buffer Overflow');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3161, NULL, NULL, 'FTP realpath Buffer Overflow');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3162, NULL, NULL, 'glFtpD LIST DoS');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3163, NULL, NULL, 'wu-ftpd heap corruption vulnerability');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3164, NULL, NULL, 'Instant Server Mini Portal Directory Traversal ');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3165, NULL, NULL, 'FTP SITE EXEC');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3166, NULL, NULL, 'FTP USER Suspicious Length');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3167, NULL, NULL, 'Format String in FTP username');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3168, NULL, NULL, 'FTP SITE EXEC Directory Traversal');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3169, NULL, NULL, 'FTP SITE EXEC tar');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3170, NULL, NULL, 'WS_FTP SITE CPWD Buffer Overflow');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3171, NULL, NULL, 'Ftp Priviledged Login');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3172, NULL, NULL, 'Ftp Cwd Overflow');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3173, NULL, NULL, 'Long FTP Command');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3175, NULL, NULL, 'ProFTPD STAT DoS');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3200, NULL, NULL, 'WWW Phf Attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3201, NULL, NULL, 'Unix Password File Access Attempt');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3202, NULL, NULL, 'WWW .url File Requested');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3203, NULL, NULL, 'WWW .lnk File Requested');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3204, NULL, NULL, 'WWW .bat File Requested');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3205, NULL, NULL, 'HTML File Has .url Link');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3206, NULL, NULL, 'HTML File Has .lnk Link');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3207, NULL, NULL, 'HTML File Has .bat Link');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3208, NULL, NULL, 'WWW campas Attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3209, NULL, NULL, 'WWW Glimpse Server Attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3210, NULL, NULL, 'WWW IIS View Source Attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3211, NULL, NULL, 'WWW IIS Hex View Source Attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3212, NULL, NULL, 'WWW NPH-TEST-CGI Attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3213, NULL, NULL, 'WWW TEST-CGI Attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3214, NULL, NULL, 'IIS DOT DOT VIEW Attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3215, NULL, NULL, 'IIS DOT DOT EXECUTE Attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3216, NULL, NULL, 'WWW Directory Traversal ../..');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3217, NULL, NULL, 'WWW php View File Attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3218, NULL, NULL, 'WWW SGI Wrap Attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3219, NULL, NULL, 'WWW PHP Buffer Overflow');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3220, NULL, NULL, 'IIS Long URL Crash Bug');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3221, NULL, NULL, 'WWW cgi-viewsource Attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3222, NULL, NULL, 'WWW PHP Log Scripts Read Attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3223, NULL, NULL, 'WWW IRIX cgi-handler Attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3224, NULL, NULL, 'HTTP WebGais');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3225, NULL, NULL, 'WWW websendmail File Access');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3226, NULL, NULL, 'WWW Webdist Bug');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3227, NULL, NULL, 'WWW Htmlscript Bug');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3228, NULL, NULL, 'WWW Performer Bug');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3229, NULL, NULL, 'Website Win-C-Sample Buffer Overflow');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3230, NULL, NULL, 'Website Uploader');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3231, NULL, NULL, 'Novell convert');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3232, NULL, NULL, 'WWW finger attempt');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3233, NULL, NULL, 'WWW count-cgi Overflow');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3250, NULL, NULL, 'TCP Hijack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3251, NULL, NULL, 'TCP Hijacking Simplex Mode');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3300, NULL, NULL, 'NetBIOS OOB Data');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3301, NULL, NULL, 'NETBIOS Stat');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3302, NULL, NULL, 'NETBIOS Session Setup Failure');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3303, NULL, NULL, 'Windows Guest Login');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3304, NULL, NULL, 'Windows Null Account Name');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3305, NULL, NULL, 'Windows Password File Access');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3306, NULL, NULL, 'Windows Registry Access');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3307, NULL, NULL, 'Windows Redbutton Attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3308, NULL, NULL, 'Windows LSARPC Access');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3309, NULL, NULL, 'Windows SRVSVC Access');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3310, NULL, NULL, 'Netbios Enum Share DoS');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3311, NULL, NULL, 'SMB: remote SAM service access attempt');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3312, NULL, NULL, 'SMB .eml email file remote access');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3313, NULL, NULL, 'SMB suspicous password usage');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3314, NULL, NULL, 'Windows Locator Service Overflow');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3320, NULL, NULL, 'SMB: ADMIN$ hidden share access attempt');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3321, NULL, NULL, 'SMB: User Enumeration');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3322, NULL, NULL, 'SMB: Windows Share Enumeration');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3323, NULL, NULL, 'SMB: RFPoison Attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3324, NULL, NULL, 'SMB NIMDA infected file transfer');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3325, NULL, NULL, 'Samba call_trans2open Overflow');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3326, NULL, NULL, 'Windows Startup Folder Remote Access');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3400, NULL, NULL, 'Sunkill');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3401, NULL, NULL, 'Telnet-IFS Match');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3402, NULL, NULL, 'BSD Telnet Daemon Buffer Overflow');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3403, NULL, NULL, 'Telnet Excessive Environment Options');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3404, NULL, NULL, 'SysV /bin/login Overflow');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3405, NULL, NULL, 'Avirt Gateway proxy Buffer Overflow ');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3406, NULL, NULL, 'Solaris TTYPROMPT /bin/login Overflow');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3450, NULL, NULL, 'Finger Bomb');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3451, NULL, NULL, 'BearShare Directory Traversal');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3452, NULL, NULL, 'gopherd halidate overflow');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3453, NULL, NULL, 'MS NetMeeting RDS DoS');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3454, NULL, NULL, 'Check Point Firewall Information Leak');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3455, NULL, NULL, 'Java Web Server Cmd Exec');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3456, NULL, NULL, 'Solaris in.fingerd Information Leak');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3457, NULL, NULL, 'Finger root shell');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3458, NULL, NULL, 'AIM game invite overflow');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3459, NULL, NULL, 'ValiCert forms.exe overflow ');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3461, NULL, NULL, 'Finger probe');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3462, NULL, NULL, 'Finger Redirect');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3463, NULL, NULL, 'Finger root');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3464, NULL, NULL, 'File access in finger');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3465, NULL, NULL, 'Finger Activity');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3500, NULL, NULL, 'Rlogin -froot Attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3501, NULL, NULL, 'Rlogin Long TERM Variable');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3502, NULL, NULL, 'rlogin Activity');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3525, NULL, NULL, 'IMAP Authenticate Buffer Overflow');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3526, NULL, NULL, 'Imap Login Buffer Overflow');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3530, NULL, NULL, 'Cisco Secure ACS Oversized TACACS+ Attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3540, NULL, NULL, 'Cisco Secure ACS CSAdmin Attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3550, NULL, NULL, 'POP Buffer Overflow');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3551, NULL, NULL, 'POP User Root');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3575, NULL, NULL, 'INN Buffer Overflow');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3576, NULL, NULL, 'INN Control Message Exploit');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3600, NULL, NULL, 'IOS Telnet Buffer Overflow');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3601, NULL, NULL, 'IOS Command History Exploit');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3602, NULL, NULL, 'Cisco IOS Identity');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3603, NULL, NULL, 'IOS Enable Bypass');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3604, NULL, NULL, 'Cisco Catalyst CR DoS');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3650, NULL, NULL, 'SSH RSAREF2 Buffer Overflow');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3651, NULL, NULL, 'SSH CRC32 Overflow');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3652, NULL, NULL, 'SSH Gobbles');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3700, NULL, NULL, 'CDE dtspcd overflow');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3701, NULL, NULL, 'Oracle 9iAS Web Cache Buffer Overflow');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3702, NULL, NULL, 'Default sa account access');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3703, NULL, NULL, 'Squid FTP URL Buffer Overflow');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3704, NULL, NULL, 'IIS FTP STAT Denial of Service');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3705, NULL, NULL, 'Tivoli Storage Manager Client Acceptor Overflow');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3706, NULL, NULL, 'MIT PGP Public Key Server Overflow');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3707, NULL, NULL, 'Perl fingerd Command Exec');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3708, NULL, NULL, 'AnalogX Proxy Socks4a DNS Overflow');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3709, NULL, NULL, 'AnalogX Proxy Web Proxy Overflow');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3710, NULL, NULL, 'Cisco Secure ACS Directory Traversal');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3711, NULL, NULL, 'Informer FW1 auth replay DoS');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3714, NULL, NULL, 'Oracle TNS \'Service_Name\' Overflow');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3728, NULL, NULL, 'Long pop username');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3729, NULL, NULL, 'Long pop password');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3730, NULL, NULL, 'Trinoo (TCP)');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3731, NULL, NULL, 'IMail HTTP Get Buffer Overflow');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3732, NULL, NULL, 'MSSQL xp_cmdshell Usage');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3990, NULL, NULL, 'BackOrifice BO2K TCP Non Stealth');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3991, NULL, NULL, 'BackOrifice BO2K TCP Stealth 1');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3992, NULL, NULL, 'BackOrifice BO2K TCP Stealth 2');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4000, NULL, NULL, 'UDP Packet');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4001, NULL, NULL, 'UDP Port Sweep');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4002, NULL, NULL, 'UDP Flood');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4003, NULL, NULL, 'Nmap UDP Port Sweep');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4050, NULL, NULL, 'UDP Bomb');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4051, NULL, NULL, 'Snork');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4052, NULL, NULL, 'Chargen DoS');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4053, NULL, NULL, 'Back Orifice');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4054, NULL, NULL, 'RIP Trace');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4055, NULL, NULL, 'BackOrifice BO2K UDP');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4056, NULL, NULL, 'NTPd readvar overflow');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4058, NULL, NULL, 'UPnP LOCATION Overflow');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4060, NULL, NULL, 'Back Orifice Ping');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4061, NULL, NULL, 'Chargen Echo DoS');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4100, NULL, NULL, 'Tftp Passwd File');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4101, NULL, NULL, 'Cisco TFTPD Directory Traversal');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4150, NULL, NULL, 'Ascend Denial of Service');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4500, NULL, NULL, 'Cisco IOS Embedded SNMP Community Names');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4501, NULL, NULL, 'Cisco CVCO/4K Remote Username/Password return');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4502, NULL, NULL, 'SNMP Password Brute Force Attempt');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4503, NULL, NULL, 'SNMP NT Info Retrieve');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4504, NULL, NULL, 'SNMP IOS Configuration Retrieval');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4505, NULL, NULL, 'SNMP VACM MIB Access');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4506, NULL, NULL, 'D-Link Wireless SNMP Plain Text Password ');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4507, NULL, NULL, 'SNMP Protocol Violation');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4508, NULL, NULL, 'Non SNMP Traffic');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4509, NULL, NULL, 'HP Openview SNMP Hidden Community Name');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4510, NULL, NULL, 'Solaris SNMP Hidden Community Name');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4511, NULL, NULL, 'Avaya SNMP Hidden Community Name');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4600, NULL, NULL, 'IOS UDP Bomb');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4601, NULL, NULL, 'CheckPoint Firewall RDP Bypass');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4603, NULL, NULL, 'DHCP Discover');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4604, NULL, NULL, 'DHCP Request');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4605, NULL, NULL, 'DHCP Offer');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4606, NULL, NULL, 'Cisco TFTP Long Filename Buffer Overflow');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4607, NULL, NULL, 'Deep Throat Response');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4608, NULL, NULL, 'Trinoo (UDP)');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4609, NULL, NULL, 'Orinoco SNMP Info Leak ');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4610, NULL, NULL, 'Kerberos 4 User Recon');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4611, NULL, NULL, 'D-Link DWL-900AP+ TFTP Config Retrieve');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4612, NULL, NULL, 'Cisco IP Phone TFTP Config Retrieve');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4613, NULL, NULL, 'TFTP Filename Buffer Overflow');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4701, NULL, NULL, 'MS-SQL Control Overflow');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5034, NULL, NULL, 'WWW IIS newdsn attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5035, NULL, NULL, 'HTTP cgi HylaFAX Faxsurvey');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5036, NULL, NULL, 'WWW Windows Password File Access Attempt');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5037, NULL, NULL, 'WWW SGI MachineInfo Attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5038, NULL, NULL, 'WWW wwwsql file read Bug');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5039, NULL, NULL, 'WWW finger attempt');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5040, NULL, NULL, 'WWW Perl Interpreter Attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5041, NULL, NULL, 'WWW anyform attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5042, NULL, NULL, 'WWW CGI Valid Shell Access');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5043, NULL, NULL, 'WWW Cold Fusion Attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5044, NULL, NULL, 'WWW Webcom.se Guestbook attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5045, NULL, NULL, 'WWW xterm display attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5046, NULL, NULL, 'WWW dumpenv.pl recon');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5047, NULL, NULL, 'WWW Server Side Include POST attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5048, NULL, NULL, 'WWW IIS BAT EXE attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5049, NULL, NULL, 'WWW IIS showcode.asp access');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5050, NULL, NULL, 'WWW IIS .htr Overflow Attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5051, NULL, NULL, 'IIS Double Byte Code Page');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5052, NULL, NULL, 'FrontPage Extensions PWD Open Attempt');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5053, NULL, NULL, 'FrontPage _vti_bin Directory List Attempt');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5054, NULL, NULL, 'WWWBoard Password');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5055, NULL, NULL, 'HTTP Basic Authentication Overflow');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5056, NULL, NULL, 'WWW Cisco IOS %% DoS');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5057, NULL, NULL, 'WWW Sambar Samples');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5058, NULL, NULL, 'WWW info2www Attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5059, NULL, NULL, 'WWW Alibaba Attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5060, NULL, NULL, 'WWW Excite AT-generate.cgi Access');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5061, NULL, NULL, 'WWW catalog_type.asp Access');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5062, NULL, NULL, 'WWW classifieds.cgi Attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5063, NULL, NULL, 'WWW dmblparser.exe Access');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5064, NULL, NULL, 'WWW imagemap.cgi Attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5065, NULL, NULL, 'WWW IRIX infosrch.cgi Attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5066, NULL, NULL, 'WWW man.sh Access');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5067, NULL, NULL, 'WWW plusmail Attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5068, NULL, NULL, 'WWW formmail.pl Access');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5069, NULL, NULL, 'WWW whois_raw.cgi Attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5070, NULL, NULL, 'WWW msadcs.dll Access');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5071, NULL, NULL, 'WWW msacds.dll Attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5072, NULL, NULL, 'WWW bizdb1-search.cgi Attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5073, NULL, NULL, 'WWW EZshopper loadpage.cgi Attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5074, NULL, NULL, 'WWW EZshopper search.cgi Attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5075, NULL, NULL, 'WWW IIS Virtualized UNC Bug');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5076, NULL, NULL, 'WWW webplus bug');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5077, NULL, NULL, 'WWW Excite AT-admin.cgi Access');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5078, NULL, NULL, 'WWW Piranha passwd attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5079, NULL, NULL, 'WWW PCCS MySQL Admin Access');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5080, NULL, NULL, 'WWW IBM WebSphere Access');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5081, NULL, NULL, 'WWW WinNT cmd.exe Access');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5083, NULL, NULL, 'WWW Virtual Vision FTP Browser Access');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5084, NULL, NULL, 'WWW Alibaba Attack 2');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5085, NULL, NULL, 'WWW IIS Source Fragment Access');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5086, NULL, NULL, 'WWW WEBactive Logfile Access');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5087, NULL, NULL, 'WWW Sun Java Server Access');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5088, NULL, NULL, 'WWW Akopia MiniVend Access');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5089, NULL, NULL, 'WWW Big Brother Directory Access');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5090, NULL, NULL, 'WWW FrontPage htimage.exe Access');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5091, NULL, NULL, 'WWW Cart32 Remote Admin Access');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5092, NULL, NULL, 'WWW CGI-World Poll It Access');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5093, NULL, NULL, 'WWW PHP-Nuke admin.php3 Access');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5095, NULL, NULL, 'WWW CGI Script Center Account Manager Attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5096, NULL, NULL, 'WWW CGI Script Center Subscribe Me Attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5097, NULL, NULL, 'WWW FrontPage MS-DOS Device Attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5099, NULL, NULL, 'WWW GWScripts News Publisher Access');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5100, NULL, NULL, 'WWW CGI Center Auction Weaver File Access');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5101, NULL, NULL, 'WWW CGI Center Auction Weaver Attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5102, NULL, NULL, 'WWW phpPhotoAlbum explorer.php Access');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5103, NULL, NULL, 'WWW SuSE Apache CGI Source Access');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5104, NULL, NULL, 'WWW YaBB File Access');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5105, NULL, NULL, 'WWW Ranson Johnson mailto.cgi Attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5106, NULL, NULL, 'WWW Ranson Johnson mailform.pl Access');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5107, NULL, NULL, 'WWW Mandrake Linux /perl Access');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5108, NULL, NULL, 'WWW Netegrity Site Minder Access');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5109, NULL, NULL, 'WWW Sambar Beta search.dll Access');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5110, NULL, NULL, 'WWW SuSE Installed Packages Access');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5111, NULL, NULL, 'WWW Solaris Answerbook 2 Access');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5112, NULL, NULL, 'WWW Solaris Answerbook 2 Attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5113, NULL, NULL, 'WWW CommuniGate Pro Access');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5114, NULL, NULL, 'WWW IIS Unicode Attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5115, NULL, NULL, 'Netscape Enterprise Server with ?wp Tags');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5116, NULL, NULL, 'Endymion MailMan Remote Command Execution');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5117, NULL, NULL, 'phpGroupWare Remote Command Exec');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5118, NULL, NULL, 'eWave ServletExec 3.0C File Upload');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5119, NULL, NULL, 'CGI Script Center News Update Admin Passwd Change');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5120, NULL, NULL, 'Netscape Server Suite Buffer Overflow');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5121, NULL, NULL, 'iPlanet .shtml Buffer Overflow');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5122, NULL, NULL, 'Nokia IP440 Denial of Service');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5123, NULL, NULL, 'WWW IIS Internet Printing Overflow');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5124, NULL, NULL, 'IIS CGI Double Decode');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5125, NULL, NULL, 'PerlCal Directory Traversal');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5126, NULL, NULL, 'WWW IIS .ida Indexing Service Overflow');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5127, NULL, NULL, 'WWW viewsrc.cgi Directory Traversal');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5128, NULL, NULL, 'WWW nph-maillist.pl Cmd Exec');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5129, NULL, NULL, 'IOS HTTP Unauth Command Execution');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5130, NULL, NULL, 'Bugzilla globals.pl');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5131, NULL, NULL, 'talkback.cgi Directory Traversal');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5132, NULL, NULL, 'VirusScan catinfo Buffer Overflow');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5133, NULL, NULL, 'Net.Commerce Macro Path Disclosure');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5134, NULL, NULL, 'MacOS PWS DoS');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5138, NULL, NULL, 'Oracle Application Server Shared Library Overflow');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5140, NULL, NULL, 'Net.Commerce Macro Denial of Service');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5141, NULL, NULL, 'NCM content.pl SQL Query Vulnerability');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5142, NULL, NULL, 'DCShop File Disclosure');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5146, NULL, NULL, 'MS-DOS Device Name DoS');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5147, NULL, NULL, 'Arcadia Internet Store Directory Traversal Attempt');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5148, NULL, NULL, 'Perception LiteServe Web Server CGI Script Source Code');


