-- ntop
-- type: monitor
-- plugin_id: 2005
--
-- $Id: ntop-monitor.sql,v 1.3 2007/08/03 11:35:49 alberto_r Exp $
--
DELETE FROM plugin WHERE id = "2005";
DELETE FROM plugin_sid where plugin_id = "2005";


INSERT INTO plugin (id, type, name, description) VALUES (2005, 2, 'ntop', 'NTop');

INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 1, NULL, NULL, 'ntop: firstSeen');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 2, NULL, NULL, 'ntop: lastSeen');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 3, NULL, NULL, 'ntop: minTTL');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 4, NULL, NULL, 'ntop: maxTTL');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 5, NULL, NULL, 'ntop: pktSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 6, NULL, NULL, 'ntop: pktRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 7, NULL, NULL, 'ntop: bytesSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 8, NULL, NULL, 'ntop: bytesRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 9, NULL, NULL, 'ntop: pktDuplicatedAckSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 10, NULL, NULL, 'ntop: pktDuplicatedAckRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 11, NULL, NULL, 'ntop: pktBroadcastSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 12, NULL, NULL, 'ntop: bytesMulticastSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 13, NULL, NULL, 'ntop: pktMulticastSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 14, NULL, NULL, 'ntop: bytesMulticastRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 15, NULL, NULL, 'ntop: pktMulticastRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 16, NULL, NULL, 'ntop: bytesSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 17, NULL, NULL, 'ntop: bytesSentLoc');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 18, NULL, NULL, 'ntop: bytesSentRem');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 19, NULL, NULL, 'ntop: bytesRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 20, NULL, NULL, 'ntop: bytesRcvdLoc');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 21, NULL, NULL, 'ntop: bytesRcvdFromRem');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 22, NULL, NULL, 'ntop: actualRcvdThpt');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 23, NULL, NULL, 'ntop: lastHourRcvdThpt');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 24, NULL, NULL, 'ntop: averageRcvdThpt');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 25, NULL, NULL, 'ntop: peakRcvdThpt');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 26, NULL, NULL, 'ntop: actualSentThpt');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 27, NULL, NULL, 'ntop: lastHourSentThpt');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 28, NULL, NULL, 'ntop: averageSentThpt');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 29, NULL, NULL, 'ntop: peakSentThpt');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 30, NULL, NULL, 'ntop: actualTThpt');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 31, NULL, NULL, 'ntop: averageTThpt');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 32, NULL, NULL, 'ntop: peakTThpt');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 33, NULL, NULL, 'ntop: actualRcvdPktThpt');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 34, NULL, NULL, 'ntop: averageRcvdPktThpt');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 35, NULL, NULL, 'ntop: peakRcvdPktThpt');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 36, NULL, NULL, 'ntop: actualSentPktThpt');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 37, NULL, NULL, 'ntop: averageSentPktThpt');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 38, NULL, NULL, 'ntop: peakSentPktThpt');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 39, NULL, NULL, 'ntop: actualTPktThpt');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 40, NULL, NULL, 'ntop: averageTPktThpt');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 41, NULL, NULL, 'ntop: peakTPktThpt');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 42, NULL, NULL, 'ntop: ipBytesSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 43, NULL, NULL, 'ntop: ipBytesRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 44, NULL, NULL, 'ntop: tcpBytesSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 45, NULL, NULL, 'ntop: tcpBytesRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 46, NULL, NULL, 'ntop: udpBytesSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 47, NULL, NULL, 'ntop: udpBytesRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 48, NULL, NULL, 'ntop: icmpSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 49, NULL, NULL, 'ntop: icmpRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 50, NULL, NULL, 'ntop: tcpSentRem');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 51, NULL, NULL, 'ntop: udpSentLoc');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 52, NULL, NULL, 'ntop: udpSentRem');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 53, NULL, NULL, 'ntop: ospfSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 54, NULL, NULL, 'ntop: igmpSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 55, NULL, NULL, 'ntop: tcpRcvdLoc');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 56, NULL, NULL, 'ntop: tcpRcvdFromRem');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 57, NULL, NULL, 'ntop: udpRcvdLoc');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 58, NULL, NULL, 'ntop: udpRcvdFromRem');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 59, NULL, NULL, 'ntop: ospfRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 60, NULL, NULL, 'ntop: igmpRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 61, NULL, NULL, 'ntop: tcpFragmentsSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 62, NULL, NULL, 'ntop: tcpFragmentsRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 63, NULL, NULL, 'ntop: udpFragmentsSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 64, NULL, NULL, 'ntop: udpFragmentsRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 65, NULL, NULL, 'ntop: icmpFragmentsSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 66, NULL, NULL, 'ntop: icmpFragmentsRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 67, NULL, NULL, 'ntop: stpSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 68, NULL, NULL, 'ntop: stpRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 69, NULL, NULL, 'ntop: ipxSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 70, NULL, NULL, 'ntop: ipxRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 71, NULL, NULL, 'ntop: osiSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 72, NULL, NULL, 'ntop: osiRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 73, NULL, NULL, 'ntop: dlcSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 74, NULL, NULL, 'ntop: dlcRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 75, NULL, NULL, 'ntop: arp_rarpSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 76, NULL, NULL, 'ntop: arp_rarpRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 77, NULL, NULL, 'ntop: arpReqPktsSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 78, NULL, NULL, 'ntop: arpReplyPktsSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 79, NULL, NULL, 'ntop: arpReplyPktsRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 80, NULL, NULL, 'ntop: decnetSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 81, NULL, NULL, 'ntop: decnetRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 82, NULL, NULL, 'ntop: appletalkSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 83, NULL, NULL, 'ntop: appletalkRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 84, NULL, NULL, 'ntop: netbiosSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 85, NULL, NULL, 'ntop: netbiosRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 86, NULL, NULL, 'ntop: ipv6Sent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 87, NULL, NULL, 'ntop: ipv6Rcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 88, NULL, NULL, 'ntop: otherSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 89, NULL, NULL, 'ntop: otherRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 90, NULL, NULL, 'ntop: securityPkts synPktsSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 91, NULL, NULL, 'ntop: securityPkts synPktsRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 92, NULL, NULL, 'ntop: securityPkts rstPktsSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 93, NULL, NULL, 'ntop: securityPkts rstPktsRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 94, NULL, NULL, 'ntop: securityPkts rstAckPktsSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 95, NULL, NULL, 'ntop: securityPkts rstAckPktsRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 96, NULL, NULL, 'ntop: securityPkts synFinPktsSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 97, NULL, NULL, 'ntop: securityPkts synFinPktsRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 98, NULL, NULL, 'ntop: securityPkts finPushUrgPktsSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 99, NULL, NULL, 'ntop: securityPkts finPushUrgPktsRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 100, NULL, NULL, 'ntop: securityPkts nullPktsSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 101, NULL, NULL, 'ntop: securityPkts nullPktsRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 102, NULL, NULL, 'ntop: securityPkts ackScanSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 103, NULL, NULL, 'ntop: securityPkts ackScanRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 104, NULL, NULL, 'ntop: securityPkts xmasScanSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 105, NULL, NULL, 'ntop: securityPkts xmasScanRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 106, NULL, NULL, 'ntop: securityPkts finScanSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 107, NULL, NULL, 'ntop: securityPkts finScanRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 108, NULL, NULL, 'ntop: securityPkts nullScanSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 109, NULL, NULL, 'ntop: securityPkts nullScanRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 110, NULL, NULL, 'ntop: securityPkts rejectedTCPConnSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 111, NULL, NULL, 'ntop: securityPkts rejectedTCPConnRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 112, NULL, NULL, 'ntop: securityPkts establishedTCPConnSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 113, NULL, NULL, 'ntop: securityPkts establishedTCPConnRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 114, NULL, NULL, 'ntop: securityPkts terminatedTCPConnServer');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 115, NULL, NULL, 'ntop: securityPkts terminatedTCPConnClient');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 116, NULL, NULL, 'ntop: securityPkts udpToClosedPortSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 117, NULL, NULL, 'ntop: securityPkts udpToClosedPortRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 118, NULL, NULL, 'ntop: securityPkts udpToDiagnosticPortSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 119, NULL, NULL, 'ntop: securityPkts udpToDiagnosticPortRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 120, NULL, NULL, 'ntop: securityPkts tcpToDiagnosticPortSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 121, NULL, NULL, 'ntop: securityPkts tcpToDiagnosticPortRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 122, NULL, NULL, 'ntop: securityPkts tinyFragmentSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 123, NULL, NULL, 'ntop: securityPkts tinyFragmentRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 124, NULL, NULL, 'ntop: securityPkts icmpFragmentSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 125, NULL, NULL, 'ntop: securityPkts icmpFragmentRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 126, NULL, NULL, 'ntop: securityPkts overlappingFragmentSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 127, NULL, NULL, 'ntop: securityPkts overlappingFragmentRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 128, NULL, NULL, 'ntop: securityPkts closedEmptyTCPConnSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 129, NULL, NULL, 'ntop: securityPkts closedEmptyTCPConnRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 130, NULL, NULL, 'ntop: securityPkts icmpPortUnreachSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 131, NULL, NULL, 'ntop: securityPkts icmpPortUnreachRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 132, NULL, NULL, 'ntop: securityPkts icmpHostNetUnreachSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 133, NULL, NULL, 'ntop: securityPkts icmpProtocolUnreachSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 134, NULL, NULL, 'ntop: securityPkts icmpProtocolUnreachRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 135, NULL, NULL, 'ntop: securityPkts icmpHostNetUnreachRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 136, NULL, NULL, 'ntop: securityPkts icmpAdminProhibitedSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 137, NULL, NULL, 'ntop: securityPkts icmpAdminProhibitedRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 138, NULL, NULL, 'ntop: securityPkts malformedPktsSent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 139, NULL, NULL, 'ntop: securityPkts malformedPktsRcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 140, NULL, NULL, 'ntop: IP FTP sentLoc');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 141, NULL, NULL, 'ntop: IP FTP sentRem');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 142, NULL, NULL, 'ntop: IP FTP rcvdLoc');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 143, NULL, NULL, 'ntop: IP FTP rcvdFromRem');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 144, NULL, NULL, 'ntop: IP HTTP sentLoc');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 145, NULL, NULL, 'ntop: IP HTTP sentRem');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 146, NULL, NULL, 'ntop: IP HTTP rcvdLoc');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 147, NULL, NULL, 'ntop: IP HTTP rcvdFromRem');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 148, NULL, NULL, 'ntop: IP DNS sentLoc');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 149, NULL, NULL, 'ntop: IP DNS sentRem');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 150, NULL, NULL, 'ntop: IP DNS rcvdLoc');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 151, NULL, NULL, 'ntop: IP DNS rcvdFromRem');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 152, NULL, NULL, 'ntop: IP Telnet sentLoc');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 153, NULL, NULL, 'ntop: IP Telnet sentRem');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 154, NULL, NULL, 'ntop: IP Telnet rcvdLoc');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 155, NULL, NULL, 'ntop: IP Telnet rcvdFromRem');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 156, NULL, NULL, 'ntop: IP NBios-IP sentLoc');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 157, NULL, NULL, 'ntop: IP NBios-IP sentRem');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 158, NULL, NULL, 'ntop: IP NBios-IP rcvdLoc');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 159, NULL, NULL, 'ntop: IP NBios-IP rcvdFromRem');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 160, NULL, NULL, 'ntop: IP Mail sentLoc');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 161, NULL, NULL, 'ntop: IP Mail sentRem');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 162, NULL, NULL, 'ntop: IP Mail rcvdLoc');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 163, NULL, NULL, 'ntop: IP Mail rcvdFromRem');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 164, NULL, NULL, 'ntop: IP DHCP-BOOTP sentLoc');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 165, NULL, NULL, 'ntop: IP DHCP-BOOTP sentRem');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 166, NULL, NULL, 'ntop: IP DHCP-BOOTP rcvdLoc');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 167, NULL, NULL, 'ntop: IP DHCP-BOOTP rcvdFromRem');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 168, NULL, NULL, 'ntop: IP SNMP sentLoc');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 169, NULL, NULL, 'ntop: IP SNMP sentRem');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 170, NULL, NULL, 'ntop: IP SNMP rcvdLoc');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 171, NULL, NULL, 'ntop: IP SNMP rcvdFromRem');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 172, NULL, NULL, 'ntop: IP NNTP sentLoc');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 173, NULL, NULL, 'ntop: IP NNTP sentRem');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 174, NULL, NULL, 'ntop: IP NNTP rcvdLoc');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 175, NULL, NULL, 'ntop: IP NNTP rcvdFromRem');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 176, NULL, NULL, 'ntop: IP NFS sentLoc');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 177, NULL, NULL, 'ntop: IP NFS sentRem');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 178, NULL, NULL, 'ntop: IP NFS rcvdLoc');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 179, NULL, NULL, 'ntop: IP NFS rcvdFromRem');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 180, NULL, NULL, 'ntop: IP X11 sentLoc');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 181, NULL, NULL, 'ntop: IP X11 sentRem');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 182, NULL, NULL, 'ntop: IP X11 rcvdLoc');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 183, NULL, NULL, 'ntop: IP X11 rcvdFromRem');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 184, NULL, NULL, 'ntop: IP SSH sentLoc');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 185, NULL, NULL, 'ntop: IP SSH sentRem');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 186, NULL, NULL, 'ntop: IP SSH rcvdLoc');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 187, NULL, NULL, 'ntop: IP SSH rcvdFromRem');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 188, NULL, NULL, 'ntop: IP Gnutella sentLoc');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 189, NULL, NULL, 'ntop: IP Gnutella sentRem');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 190, NULL, NULL, 'ntop: IP Gnutella rcvdLoc');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 191, NULL, NULL, 'ntop: IP Gnutella rcvdFromRem');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 192, NULL, NULL, 'ntop: IP Kazaa sentLoc');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 193, NULL, NULL, 'ntop: IP Kazaa sentRem');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 194, NULL, NULL, 'ntop: IP Kazaa rcvdLoc');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 195, NULL, NULL, 'ntop: IP Kazaa rcvdFromRem');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 196, NULL, NULL, 'ntop: IP WinMX sentLoc');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 197, NULL, NULL, 'ntop: IP WinMX sentRem');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 198, NULL, NULL, 'ntop: IP WinMX rcvdLoc');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 199, NULL, NULL, 'ntop: IP WinMX rcvdFromRem');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 200, NULL, NULL, 'ntop: IP DirectConnect sentLoc');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 201, NULL, NULL, 'ntop: IP DirectConnect sentRem');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 202, NULL, NULL, 'ntop: IP DirectConnect rcvdLoc');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 203, NULL, NULL, 'ntop: IP DirectConnect rcvdFromRem');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 204, NULL, NULL, 'ntop: IP eDonkey sentLoc');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 205, NULL, NULL, 'ntop: IP eDonkey sentRem');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 206, NULL, NULL, 'ntop: IP eDonkey rcvdLoc');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 207, NULL, NULL, 'ntop: IP eDonkey rcvdFromRem');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 208, NULL, NULL, 'ntop: IP Messenger sentLoc');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 209, NULL, NULL, 'ntop: IP Messenger sentRem');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 210, NULL, NULL, 'ntop: IP Messenger rcvdLoc');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 211, NULL, NULL, 'ntop: IP Messenger rcvdFromRem');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 212, NULL, NULL, 'ntop: IP PROXY sentLoc');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 213, NULL, NULL, 'ntop: IP PROXY sentRem');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 214, NULL, NULL, 'ntop: IP PROXY rcvdLoc');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 215, NULL, NULL, 'ntop: IP PROXY rcvdFromRem');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 216, NULL, NULL, 'ntop: IP NEWS sentLoc');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 217, NULL, NULL, 'ntop: IP NEWS sentRem');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 218, NULL, NULL, 'ntop: IP NEWS rcvdLoc');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 219, NULL, NULL, 'ntop: IP NEWS rcvdFromRem');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 220, NULL, NULL, 'ntop: ICMP SENT_ECHO');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 221, NULL, NULL, 'ntop: ICMP SENT_ECHOREPLY');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 222, NULL, NULL, 'ntop: ICMP SENT_UNREACH');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 223, NULL, NULL, 'ntop: ICMP SENT_ROUTERADVERT');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 224, NULL, NULL, 'ntop: ICMP SENT_TMXCEED');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 225, NULL, NULL, 'ntop: ICMP SENT_PARAMPROB');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 226, NULL, NULL, 'ntop: ICMP SENT_MASKREPLY');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 227, NULL, NULL, 'ntop: ICMP SENT_MASKREQ');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 228, NULL, NULL, 'ntop: ICMP SENT_INFO_REQUEST');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 229, NULL, NULL, 'ntop: ICMP SENT_INFO_REPLY');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 230, NULL, NULL, 'ntop: ICMP SENT_TIMESTAMP');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 231, NULL, NULL, 'ntop: ICMP SENT_TIMESTAMPREPLY');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 232, NULL, NULL, 'ntop: ICMP SENT_SOURCE_QUENCH');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 233, NULL, NULL, 'ntop: ICMP RCVD_ECHO');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 234, NULL, NULL, 'ntop: ICMP RCVD_ECHOREPLY');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 235, NULL, NULL, 'ntop: ICMP RCVD_UNREACH');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 236, NULL, NULL, 'ntop: ICMP RCVD_ROUTERADVERT');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 237, NULL, NULL, 'ntop: ICMP RCVD_TMXCEED');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 238, NULL, NULL, 'ntop: ICMP RCVD_PARAMPROB');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 239, NULL, NULL, 'ntop: ICMP RCVD_MASKREPLY');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 240, NULL, NULL, 'ntop: ICMP RCVD_MASKREQ');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 241, NULL, NULL, 'ntop: ICMP RCVD_INFO_REQUEST');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 242, NULL, NULL, 'ntop: ICMP RCVD_INFO_REPLY');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 243, NULL, NULL, 'ntop: ICMP RCVD_TIMESTAMP');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 244, NULL, NULL, 'ntop: ICMP RCVD_TIMESTAMPREPLY');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 245, NULL, NULL, 'ntop: ICMP RCVD_SOURCE_QUENCH');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 246, NULL, NULL, 'ntop: Session Data Sent');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 247, NULL, NULL, 'ntop: Session Data Rcvd');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 248, NULL, NULL, 'ntop: Session Duration');

