/* Enums
 *
 *
 *
 */

#ifndef __SIM_ENUMS_H__
#define __SIM_ENUMS_H__ 1

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#define SIM_CONFIG_FILE             "/etc/ossim.conf"

#define BUFFER_SIZE                 1024

#define GENERATOR_SPP_SPADE         104
#define GENERATOR_SPP_SCAN2         117
#define GENERATOR_SNORT_ENGINE      1

#define SNORT_DEFAULT_PRIORITY      2
#define SNORT_MAX_PRIORITY          3

#define FW1_DEFAULT_PRIORITY        1

#define GENERATOR_FW1               200
#define FW1_ACCEPT_TYPE             1
#define FW1_DROP_TYPE               2
#define FW1_REJECT_TYPE             3

#define FW1_ACCEPT_PRIORITY         0
#define FW1_DROP_PRIORITY           1
#define FW1_REJECT_PRIORITY         1

#define RRD_DEFAULT_PRIORITY        5

typedef enum
{
  SIM_PROTOCOL_TYPE_NONE,
  SIM_PROTOCOL_TYPE_ICMP,
  SIM_PROTOCOL_TYPE_UDP,
  SIM_PROTOCOL_TYPE_TCP
} SimProtocolType;

typedef enum
{
  SIM_CONFIG_PROPERTY_TYPE_NOME,
  SIM_CONFIG_PROPERTY_TYPE_LOG_FILE,
  SIM_CONFIG_PROPERTY_TYPE_DATABASE,
  SIM_CONFIG_PROPERTY_TYPE_USERNAME,
  SIM_CONFIG_PROPERTY_TYPE_PASSWORD,
  SIM_CONFIG_PROPERTY_TYPE_UPDATE_INTERVAL
}  SimConfigPropertyType;

typedef enum 
{
  SIM_SIGNATURE_TYPE_NONE,
  SIM_SIGNATURE_TYPE_GROUP,
  SIM_SIGNATURE_TYPE_SUBGROUP,
  SIM_SIGNATURE_TYPE_SIGNATURE
} SimSignatureType;

typedef enum 
{
  SIM_SIGNATURE_SUBGROUP_TYPE_NONE,
  SIM_SIGNATURE_SUBGROUP_TYPE_ATTACK_RESPONSES,
  SIM_SIGNATURE_SUBGROUP_TYPE_BACKDOOR,
  SIM_SIGNATURE_SUBGROUP_TYPE_BAD_TRAFFIC,
  SIM_SIGNATURE_SUBGROUP_TYPE_CHAT,
  SIM_SIGNATURE_SUBGROUP_TYPE_DDOS,
  SIM_SIGNATURE_SUBGROUP_TYPE_DELETED,
  SIM_SIGNATURE_SUBGROUP_TYPE_DNS,
  SIM_SIGNATURE_SUBGROUP_TYPE_DOS,
  SIM_SIGNATURE_SUBGROUP_TYPE_EXPERIMENTAL,
  SIM_SIGNATURE_SUBGROUP_TYPE_EXPLOIT,
  SIM_SIGNATURE_SUBGROUP_TYPE_FINGER,
  SIM_SIGNATURE_SUBGROUP_TYPE_FTP,
  SIM_SIGNATURE_SUBGROUP_TYPE_FW1_ACCEPT,
  SIM_SIGNATURE_SUBGROUP_TYPE_FW1_DROP,
  SIM_SIGNATURE_SUBGROUP_TYPE_FW1_REJECT,
  SIM_SIGNATURE_SUBGROUP_TYPE_ICMP,
  SIM_SIGNATURE_SUBGROUP_TYPE_ICMP_INFO,
  SIM_SIGNATURE_SUBGROUP_TYPE_IMAP,
  SIM_SIGNATURE_SUBGROUP_TYPE_INFO,
  SIM_SIGNATURE_SUBGROUP_TYPE_LOCAL,
  SIM_SIGNATURE_SUBGROUP_TYPE_MISC,
  SIM_SIGNATURE_SUBGROUP_TYPE_MULTIMEDIA,
  SIM_SIGNATURE_SUBGROUP_TYPE_MYSQL,
  SIM_SIGNATURE_SUBGROUP_TYPE_NETBIOS,
  SIM_SIGNATURE_SUBGROUP_TYPE_NNTP,
  SIM_SIGNATURE_SUBGROUP_TYPE_ORACLE,
  SIM_SIGNATURE_SUBGROUP_TYPE_OTHER_IDS,
  SIM_SIGNATURE_SUBGROUP_TYPE_P2P,
  SIM_SIGNATURE_SUBGROUP_TYPE_POLICY,
  SIM_SIGNATURE_SUBGROUP_TYPE_POP2,
  SIM_SIGNATURE_SUBGROUP_TYPE_POP3,
  SIM_SIGNATURE_SUBGROUP_TYPE_PORN,
  SIM_SIGNATURE_SUBGROUP_TYPE_RPC,
  SIM_SIGNATURE_SUBGROUP_TYPE_RSERVICES,
  SIM_SIGNATURE_SUBGROUP_TYPE_SCAN,
  SIM_SIGNATURE_SUBGROUP_TYPE_SHELLCODE,
  SIM_SIGNATURE_SUBGROUP_TYPE_SMTP,
  SIM_SIGNATURE_SUBGROUP_TYPE_SNMP,
  SIM_SIGNATURE_SUBGROUP_TYPE_SPADE,
  SIM_SIGNATURE_SUBGROUP_TYPE_SQL,
  SIM_SIGNATURE_SUBGROUP_TYPE_TELNET,
  SIM_SIGNATURE_SUBGROUP_TYPE_TFTP,
  SIM_SIGNATURE_SUBGROUP_TYPE_VIRUS,
  SIM_SIGNATURE_SUBGROUP_TYPE_WEB_ATTACKS,
  SIM_SIGNATURE_SUBGROUP_TYPE_WEB_CGI,
  SIM_SIGNATURE_SUBGROUP_TYPE_WEB_CLIENT,
  SIM_SIGNATURE_SUBGROUP_TYPE_WEB_COLDFUSION,
  SIM_SIGNATURE_SUBGROUP_TYPE_WEB_FRONTPAGE,
  SIM_SIGNATURE_SUBGROUP_TYPE_WEB_IIS,
  SIM_SIGNATURE_SUBGROUP_TYPE_WEB_MISC,
  SIM_SIGNATURE_SUBGROUP_TYPE_WEB_PHP,
  SIM_SIGNATURE_SUBGROUP_TYPE_X11
} SimSignatureSubgroupType;

typedef enum {
  SIM_MESSAGE_TYPE_INVALID,
  SIM_MESSAGE_TYPE_SNORT,
  SIM_MESSAGE_TYPE_LOGGER,
  SIM_MESSAGE_TYPE_RRD
} SimMessageType;

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* __SIM_ENUMS_H__ */
