#!/bin/bash
#
# Init file for the OSSIM framework 
#
# description: Ossim framework
#
# processname: ossim-framework
# config: /etc/ossim/framework/ossim.conf

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ -x "/usr/bin/python" ] || exit 1
[ -r "/usr/bin/ossim-framework" ] || exit 1
[ -r "/etc/ossim/framework/ossim.conf" ] || exit 1

RETVAL=0
prog="ossim-framework"

start () {
	echo -n $"Starting $prog: "
	daemon $prog -d -c /etc/ossim/framework/ossim.conf
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && touch /var/lock/subsys/\$prog
	return $RETVAL
}

stop () {
	echo -n $"Stopping $prog: "
	killproc $prog
	RETVAL=$?
	echo 
	[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/$prog
	return $RETVAL
}

restart () {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  condrestart)
	[ -e /var/lock/subsys/$prog ] && restart
	RETVAL=$?
	;;
  status)
	status $prog
	RETVAL=$?
	;;
  *)
	echo $"Usage: $0 {start|stop|restart|condrestart|status}"
	RETVAL=1
esac

exit $RETVAL
