#!/bin/bash
#
# Init file for the OSSIM server 
#
# description: Ossim server
#
# processname: ossim-server
# config: /etc/ossim/server/config.xml

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check networking
[ "${NETWORKING}" == "no" ] && exit 0
# Check ossim-server file
[ -x "/usr/bin/ossim-server" ] || exit 1
# Check ossim-server config file
[ -r "/etc/ossim/server/config.xml" ] || exit 1

RETVAL=0
prog="ossim-server"

start () {
	echo -n $"Starting $prog: "
	daemon $prog -d -c /etc/ossim/server/config.xml
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && touch /var/lock/subsys/\$prog
	return $RETVAL
}

stop () {
	echo -n $"Stopping $prog: "
	killproc $prog
	RETVAL=$?
	echo 
	[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/$prog
	return $RETVAL
}

restart () {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  condrestart)
	[ -e /var/lock/subsys/$prog ] && restart
	RETVAL=$?
	;;
  status)
	status $prog
	RETVAL=$?
	;;
  *)
	echo $"Usage: $0 {start|stop|restart|condrestart|status}"
	RETVAL=1
esac

exit $RETVAL
