<?php
// This file describes sample downloads available to the user.
// This could be useful for snare, osiris, openvpn and other clients for windows hosts, for example
$downloads = array(
    	array(
             "Name" => "Sample Download",
             "Version" => "1.0",
             "URL" => "demo.txt",
             "Homepage" => "http://www.ossim.net",
             "Description" => "A sample download"
             ),
	array(
             "Name" => "Sample Download 2",
             "Version" => "1.5",
             "URL" => "demo.txt",
             "Homepage" => "http://www.ossim.com",
             "Description" => "Another sample download"
             )
);
?>
