#!/usr/bin/perl

use strict;

if ($#ARGV != 2) {
    print "usage: readsids <rules_dir> -f <sids>\n";
    exit;
}

open (SIDS, "> " . $ARGV[2]) or die "Unable to open file " . $ARGV[2];
opendir(DIR, $ARGV[0]); 
while(my $name  = readdir(DIR)) {

    my $filename = $ARGV[0] . '/' . $name;

    open (FILE, $filename) or die "Unable to open file $filename";

    my $sig_name;
    my $msg;
    if ($filename =~ /([\w\d-_]+)\.rules/) { $sig_name = $1; }
    
    while ($_ = <FILE>) {
        if (/msg:([^;]+)/) {
            $msg = $1;
        }
        if (/sid:([^;]+)/) {
            my $sid = $1;
            print SIDS "$sig_name;$sid;$msg\n";
        }
    }
    
    close($filename);
}
close($ARGV[2]);

