#!/bin/sh -e

. /usr/share/debconf/confmodule

CONFIG=/etc/ossim/agent/config.xml

[ -f $CONFIG ] || exit

db_get ossim-agent/sensor || true
SENSOR=$RET
if [ "$SENSOR" != "" ]
then
    cat $CONFIG | sed "/ENTITY.*sensor/s/\".*\"/\"$SENSOR\"/g" > $CONFIG.bak
    mv $CONFIG.bak $CONFIG
fi

db_get ossim-agent/interface || true
INTERFACE=$RET
if [ "$INTERFACE" != "" ]
then
cat $CONFIG | sed "/ENTITY.*interface/s/\".*\"/\"$INTERFACE\"/g" > $CONFIG.bak
mv $CONFIG.bak $CONFIG
fi

db_get ossim-agent/serverip || true
SERVERIP=$RET
if [ "$SERVERIP" != "" ]
then
    cat $CONFIG | sed "/ENTITY.*serverip/s/\".*\"/\"$SERVERIP\"/g" > $CONFIG.bak
    mv $CONFIG.bak $CONFIG
fi


db_get ossim-agent/plugins || true
PLUGINS=$RET

TEMPFILE=`mktemp`
WRITE=1

cat $CONFIG  | while read LINE
do

    # search begin of plugins
    if [ "`echo $LINE | egrep "\s*<plugins>$"`" != "" ]
    then
        echo "<plugins>" >> $TEMPFILE
        WRITE=0

        # write plugins
        for plugin in $PLUGINS
        do
            plugin=`echo $plugin | sed -e 's/,$//g'`
            echo "&$plugin;" >> $TEMPFILE
        done
        
    fi
    
    # search end of plugins
    if [ "`echo $LINE | egrep "</plugins>$"`" != "" ]
    then
        WRITE=1
    fi

    if [ $WRITE -eq 1 ]
    then
        echo $LINE >> $TEMPFILE
    fi
done

mv -f $TEMPFILE $CONFIG


update-rc.d ossim-agent defaults 41 2&> /dev/null
#/etc/init.d/ossim-agent restart

# temporal
update-rc.d -f ossimagent remove > /dev/null
rm -f /etc/init.d/ossimagent


