#
#
#
#

# Get database info
- name: Get database IP
  action: shell executable=/bin/bash grep -m1 ^db_ip /etc/ossim/ossim_setup.conf | awk -F= {'print $2'}
  register: DB_IP
  changed_when: False


- name: Get database user
  action: shell executable=/bin/bash grep -m1 ^user /etc/ossim/ossim_setup.conf | awk -F= {'print $2'}
  register: DB_USER
  changed_when: False

- name: Get database password
  action: shell executable=/bin/bash grep -m1 ^pass /etc/ossim/ossim_setup.conf | awk -F= {'print $2'}
  register: DB_PASS
  changed_when: False