alienvault-ossec/rules0090-ossec.iptables etc/iptables/
alienvault-ossec/var/ossec/rules/alienvault-directory-service_rules.xml var/ossec/rules/
alienvault-ossec/var/ossec/rules/alienvault-windows-FIM_rules.xml var/ossec/rules/
alienvault-ossec/var/ossec/rules/alienvault-windows-logon-logoff_rules.xml var/ossec/rules/
alienvault-ossec/var/ossec/rules/alienvault-windows-USB_rules.xml var/ossec/rules/
alienvault-ossec/var/ossec/.ssh/config var/ossec/.ssh/
