#!/bin/bash

backup_dir=`grep ^backup_dir /etc/ossim/framework/ossim.conf | cut -d= -f2`
user=`grep ^ossim_user /etc/ossim/framework/ossim.conf | cut -d= -f2`
pass=`grep ^ossim_pass /etc/ossim/framework/ossim.conf | cut -d= -f2`
base=`grep ^ossim_base /etc/ossim/framework/ossim.conf | cut -d= -f2`

date=`date +%Y%m%d`

mysqldump -u $user -p$pass $base > $backup_dir/ossim-$date.dump
gzip $backup_dir/ossim-$date.dump

