#!/bin/bash

CONF=/etc/ossim/framework/ossim.conf
[ -f "$CONF" ] || exit

HOST=`grep ^ossim_host $CONF | cut -d= -f2`
USER=`grep ^ossim_user $CONF | cut -d= -f2`
PASS=`grep ^ossim_pass $CONF | cut -d= -f2`
BASE=`grep ^ossim_base $CONF | cut -d= -f2`

ACL_HOST=`grep ^phpgacl_host $CONF | cut -d= -f2`
ACL_USER=`grep ^phpgacl_user $CONF | cut -d= -f2`
ACL_PASS=`grep ^phpgacl_pass $CONF | cut -d= -f2`
ACL_BASE=`grep ^phpgacl_base $CONF | cut -d= -f2`

BACKUP=/var/lib/ossim/backup/ossim-backup_`date '+%F'`.sql.gz

mysqldump -h $HOST -u $USER -p$PASS $BASE | gzip -9c > $BACKUP

if [ $ACL_BASE != $BASE ]; then
	ACL_BACKUP=/var/lib/ossim/backup/ossim-backup_acls_`date '+%F'`.sql.gz
	mysqldump -h $ACL_HOST -u $ACL_USER -p$ACL_PASS $ACL_BASE | gzip -9c > $ACL_BACKUP
fi	
