#!/bin/bash

export LANG=C

MRTG=/usr/bin/mrtg
data_dir=`grep ^data_dir /etc/ossim/framework/ossim.conf | cut -d= -f2`

cd $data_dir/mrtg/hosts
./create_cfg.pl

cd $data_dir/mrtg/nets
./create_cfg.pl

cd $data_dir/mrtg/global
./create_cfg.pl

cd $data_dir/mrtg/level
./create_cfg.pl

`$MRTG /etc/ossim/framework/mrtg-rrd.cfg`

