#!/bin/bash

base_dir=`grep ^base_dir /etc/ossim.conf | cut -d= -f2`

cd $base_dir/mrtg/hosts
./create_cfg.pl

cd $base_dir/mrtg/nets
./create_cfg.pl

cd $base_dir/mrtg/global
./create_cfg.pl

/usr/bin/mrtg /etc/mrtg.cfg
/usr/bin/mrtg /etc/mrtg-rrd.cfg

