#!/bin/bash

export LANG=C

base_dir=`grep ^base_dir /etc/ossim.conf | cut -d= -f2`
mrtg_path=`grep ^mrtg_path /etc/ossim.conf | cut -d= -f2`

cd $base_dir/mrtg/hosts
./create_cfg.pl

cd $base_dir/mrtg/nets
./create_cfg.pl

cd $base_dir/mrtg/global
./create_cfg.pl

`$mrtg_path/mrtg /etc/mrtg.cfg`
`$mrtg_path/mrtg /etc/mrtg-rrd.cfg`

